name: 'Setup QEMU'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - if: runner.os == 'Linux'       # https://www.qemu.org/download/#linux
      shell: bash
      run: sudo apt-get update && sudo apt-get install qemu qemu-system

    - if: runner.os == 'macOS'       # https://www.qemu.org/download/#macos
      shell: bash
      run: brew update && brew install qemu

    - if: runner.os == 'Windows'     # https://www.qemu.org/download/#windows
      shell: bash
      run: |
          C:/msys64/usr/bin/yes.exe | C:/msys64/usr/bin/pacman.exe -S mingw-w64-ucrt-x86_64-qemu
          echo "C:\msys64\ucrt64\bin" >> $GITHUB_PATH
