name: Test setup-qemu

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.host }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        host: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.
      - if: runner.os == 'Linux'
        run:  compgen -c | grep qemu
      - if: runner.os == 'Windows'
        run:  ls -R C:/msys64
      - run:  qemu-system-x86_64 --version
